web:
  vars:
    MDA_ENV: dev

strapi:
  ~needs: [build-strapi]

jobs:
  runs:
    build-web:
      with:
        buildArgs:
          PRODUCTION: "true"
    create-db:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
    build-strapi:
      ~needs: [create-db]
