# global:
#   host: maisonautisme.gouv.fr #TODO enable when domain is ok

app:
  vars:
    MDA_ENV: prod

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          PRODUCTION: "true"
          ROBOT: "true"
