projectName: mda
repositoryName: mda

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique

environmentPatterns:
  prod: false
  preprod: dev
  dev:
    - "!v*"
    - "!main"
    - "!dev"
