global:
  registry: harbor.fabrique.social.gouv.fr
  imageProject: mda
  imageRepository: mda

app:
  ~needs: [build-app]
  imagePackage: app
  probesPath: /healthz
  host: "{{ .Values.global.host }}"

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        registrySecretRefName: harbor
        skipExisting: true
        buildOptions: --single-snapshot --ignore-path=/product_uuid --compressed-caching=false # optim for local builds
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"