global:
  registry: harbor.fabrique.social.gouv.fr
  imageProject: maison-de-l-autisme
  imageRepository: mda

web:
  ~chart: app
  ~needs: [build-web]
  imagePackage: web
  probesPath: /healthz
  host: "{{ .Values.global.host }}"
  vars:
    NEXT_PUBLIC_SITE_URL: "{{ .Values.global.host }}"

strapi:
  ~chart: app
  ~needs: [build-strapi]
  imagePackage: strapi
  probesPath: /_health
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: "mda-strapi"
  vars:
    DATABASE_HOST: "$(PGHOST)"
    DATABASE_PORT: "$(PGPORT)"
    DATABASE_NAME: "$(PGDATABASE)"
    DATABASE_USERNAME: "$(PGUSER)"
    DATABASE_PASSWORD: "$(PGPASSWORD)"
    DATABASE_SSL: "$(PGSSLMODE)"
    HOST: "strapi.{{ .Values.global.host }}"

jobs:
  runs:
    build-web:
      ~needs: [strapi]
      use: build
      with:
        imagePackage: web
        dockerfile: apps/web/Dockerfile
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
          NEXT_PUBLIC_SITE_URL: "{{ .Values.global.host }}"
          NEXT_PUBLIC_STRAPI_API_URL: "https://strapi.{{ .Values.global.host }}"

    build-strapi:
      use: SocialGouv/kontinuous/plugins/contrib/jobs/build
      with:
        imagePackage: strapi
        dockerfile: apps/strapi/Dockerfile
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"